name: Flutter CI/CD

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout code
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Install Flutter
      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.29.0' # use your flutter version

      # Step 3: Get dependencies
      - name: Install dependencies
        run: flutter pub get

      # Step 4: Run analyzer (optional)
      - name: Analyze
        run: flutter analyze

      # Step 5: Build APK
      - name: Build APK
        run: flutter build apk --release

      # Step 6: Build AppBundle (AAB)
      - name: Build AppBundle
        run: flutter build appbundle --release

      # Step 7: Upload APK artifact
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: apk
          path: build/app/outputs/flutter-apk/*.apk

      # Step 8: Upload AAB artifact
      - name: Upload AAB
        uses: actions/upload-artifact@v4
        with:
          name: aab
          path: build/app/outputs/bundle/release/*.aab
